//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 02:49:25 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for course complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="course">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="allowedEnrollmentCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="approvalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classesLang" type="{http://kosapi.feld.cvut.cz/schema/3}classesLang"/>
 *         &lt;element name="classesType" type="{http://kosapi.feld.cvut.cz/schema/3}classesType"/>
 *         &lt;element name="completion" type="{http://kosapi.feld.cvut.cz/schema/3}completion"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="department" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="description" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="homepage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keywords" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="lecturesContents" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="literature" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="name" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="note" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="objectives" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="programmeType" type="{http://kosapi.feld.cvut.cz/schema/3}programmeType"/>
 *         &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requirements" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *         &lt;element name="season" type="{http://kosapi.feld.cvut.cz/schema/3}season"/>
 *         &lt;element name="state" type="{http://kosapi.feld.cvut.cz/schema/3}courseState"/>
 *         &lt;element name="studyForm" type="{http://kosapi.feld.cvut.cz/schema/3}studyForm"/>
 *         &lt;element name="tutorialsContents" type="{http://kosapi.feld.cvut.cz/schema/3}label" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "course", propOrder = {
    "allowedEnrollmentCount",
    "approvalDate",
    "classesLang",
    "classesType",
    "completion",
    "code",
    "credits",
    "department",
    "description",
    "homepage",
    "keywords",
    "lecturesContents",
    "literature",
    "name",
    "note",
    "objectives",
    "programmeType",
    "range",
    "requirements",
    "season",
    "state",
    "studyForm",
    "tutorialsContents"
})
public class Course {

    protected Integer allowedEnrollmentCount;
    protected String approvalDate;
    protected ClassesLang classesLang;
    protected ClassesType classesType;
    protected Completion completion;
    protected String code;
    protected Integer credits;
    protected Link department;
    protected List<Label> description;
    protected String homepage;
    protected List<Label> keywords;
    protected List<Label> lecturesContents;
    protected List<Label> literature;
    protected List<Label> name;
    protected List<Label> note;
    protected List<Label> objectives;
    protected ProgrammeType programmeType;
    protected String range;
    protected List<Label> requirements;
    protected Season season;
    protected CourseState state;
    protected StudyForm studyForm;
    protected List<Label> tutorialsContents;

    /**
     * Gets the value of the allowedEnrollmentCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAllowedEnrollmentCount() {
        return allowedEnrollmentCount;
    }

    /**
     * Sets the value of the allowedEnrollmentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAllowedEnrollmentCount(Integer value) {
        this.allowedEnrollmentCount = value;
    }

    /**
     * Gets the value of the approvalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalDate() {
        return approvalDate;
    }

    /**
     * Sets the value of the approvalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalDate(String value) {
        this.approvalDate = value;
    }

    /**
     * Gets the value of the classesLang property.
     * 
     * @return
     *     possible object is
     *     {@link ClassesLang }
     *     
     */
    public ClassesLang getClassesLang() {
        return classesLang;
    }

    /**
     * Sets the value of the classesLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassesLang }
     *     
     */
    public void setClassesLang(ClassesLang value) {
        this.classesLang = value;
    }

    /**
     * Gets the value of the classesType property.
     * 
     * @return
     *     possible object is
     *     {@link ClassesType }
     *     
     */
    public ClassesType getClassesType() {
        return classesType;
    }

    /**
     * Sets the value of the classesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassesType }
     *     
     */
    public void setClassesType(ClassesType value) {
        this.classesType = value;
    }

    /**
     * Gets the value of the completion property.
     * 
     * @return
     *     possible object is
     *     {@link Completion }
     *     
     */
    public Completion getCompletion() {
        return completion;
    }

    /**
     * Sets the value of the completion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Completion }
     *     
     */
    public void setCompletion(Completion value) {
        this.completion = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the credits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * Sets the value of the credits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCredits(Integer value) {
        this.credits = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setDepartment(Link value) {
        this.department = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getDescription() {
        if (description == null) {
            description = new ArrayList<Label>();
        }
        return this.description;
    }

    /**
     * Gets the value of the homepage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * Sets the value of the homepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomepage(String value) {
        this.homepage = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<Label>();
        }
        return this.keywords;
    }

    /**
     * Gets the value of the lecturesContents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lecturesContents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLecturesContents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getLecturesContents() {
        if (lecturesContents == null) {
            lecturesContents = new ArrayList<Label>();
        }
        return this.lecturesContents;
    }

    /**
     * Gets the value of the literature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the literature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLiterature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getLiterature() {
        if (literature == null) {
            literature = new ArrayList<Label>();
        }
        return this.literature;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getName() {
        if (name == null) {
            name = new ArrayList<Label>();
        }
        return this.name;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getNote() {
        if (note == null) {
            note = new ArrayList<Label>();
        }
        return this.note;
    }

    /**
     * Gets the value of the objectives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getObjectives() {
        if (objectives == null) {
            objectives = new ArrayList<Label>();
        }
        return this.objectives;
    }

    /**
     * Gets the value of the programmeType property.
     * 
     * @return
     *     possible object is
     *     {@link ProgrammeType }
     *     
     */
    public ProgrammeType getProgrammeType() {
        return programmeType;
    }

    /**
     * Sets the value of the programmeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgrammeType }
     *     
     */
    public void setProgrammeType(ProgrammeType value) {
        this.programmeType = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRange(String value) {
        this.range = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requirements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequirements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getRequirements() {
        if (requirements == null) {
            requirements = new ArrayList<Label>();
        }
        return this.requirements;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link Season }
     *     
     */
    public Season getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link Season }
     *     
     */
    public void setSeason(Season value) {
        this.season = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link CourseState }
     *     
     */
    public CourseState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseState }
     *     
     */
    public void setState(CourseState value) {
        this.state = value;
    }

    /**
     * Gets the value of the studyForm property.
     * 
     * @return
     *     possible object is
     *     {@link StudyForm }
     *     
     */
    public StudyForm getStudyForm() {
        return studyForm;
    }

    /**
     * Sets the value of the studyForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyForm }
     *     
     */
    public void setStudyForm(StudyForm value) {
        this.studyForm = value;
    }

    /**
     * Gets the value of the tutorialsContents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tutorialsContents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTutorialsContents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getTutorialsContents() {
        if (tutorialsContents == null) {
            tutorialsContents = new ArrayList<Label>();
        }
        return this.tutorialsContents;
    }

}
