//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 02:49:25 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for teacher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="teacher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="division" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extern" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="personalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supervisionPhDStudents" type="{http://kosapi.feld.cvut.cz/schema/3}permission"/>
 *         &lt;element name="titlesPost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titlesPre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "teacher", propOrder = {
    "division",
    "email",
    "extern",
    "firstName",
    "lastName",
    "personalNumber",
    "phone",
    "stageName",
    "supervisionPhDStudents",
    "titlesPost",
    "titlesPre",
    "username"
})
public class Teacher {

    protected Link division;
    protected String email;
    protected Boolean extern;
    protected String firstName;
    protected String lastName;
    protected String personalNumber;
    protected String phone;
    protected String stageName;
    protected Permission supervisionPhDStudents;
    protected String titlesPost;
    protected String titlesPre;
    protected String username;

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setDivision(Link value) {
        this.division = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the extern property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExtern() {
        return extern;
    }

    /**
     * Sets the value of the extern property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExtern(Boolean value) {
        this.extern = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the personalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalNumber() {
        return personalNumber;
    }

    /**
     * Sets the value of the personalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalNumber(String value) {
        this.personalNumber = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the stageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * Sets the value of the stageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStageName(String value) {
        this.stageName = value;
    }

    /**
     * Gets the value of the supervisionPhDStudents property.
     * 
     * @return
     *     possible object is
     *     {@link Permission }
     *     
     */
    public Permission getSupervisionPhDStudents() {
        return supervisionPhDStudents;
    }

    /**
     * Sets the value of the supervisionPhDStudents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Permission }
     *     
     */
    public void setSupervisionPhDStudents(Permission value) {
        this.supervisionPhDStudents = value;
    }

    /**
     * Gets the value of the titlesPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlesPost() {
        return titlesPost;
    }

    /**
     * Sets the value of the titlesPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlesPost(String value) {
        this.titlesPost = value;
    }

    /**
     * Gets the value of the titlesPre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlesPre() {
        return titlesPre;
    }

    /**
     * Sets the value of the titlesPre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlesPre(String value) {
        this.titlesPre = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

}
