//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.20 at 06:32:41 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="classesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ATELIER"/>
 *     &lt;enumeration value="BLOCK"/>
 *     &lt;enumeration value="CONSULTATION"/>
 *     &lt;enumeration value="LABORATORY"/>
 *     &lt;enumeration value="LECTURE"/>
 *     &lt;enumeration value="PROJECT"/>
 *     &lt;enumeration value="PROJECT_INDV"/>
 *     &lt;enumeration value="PROJECT_TEAM"/>
 *     &lt;enumeration value="PROSEMINAR"/>
 *     &lt;enumeration value="PT_COURSE"/>
 *     &lt;enumeration value="SEMINAR"/>
 *     &lt;enumeration value="TUTORIAL"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "classesType", namespace = "http://kosapi.feld.cvut.cz/schema/3")
@XmlEnum
public enum ClassesType {

    ATELIER,
    BLOCK,
    CONSULTATION,
    LABORATORY,
    LECTURE,
    PROJECT,
    PROJECT_INDV,
    PROJECT_TEAM,
    PROSEMINAR,
    PT_COURSE,
    SEMINAR,
    TUTORIAL,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static ClassesType fromValue(String v) {
        return valueOf(v);
    }

}
