//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 02:49:25 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classesLang.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="classesLang">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CS"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="SK"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "classesLang")
@XmlEnum
public enum ClassesLang {

    CS,
    DE,
    EN,
    ES,
    FR,
    PL,
    RU,
    SK,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static ClassesLang fromValue(String v) {
        return valueOf(v);
    }

}
