//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.20 at 06:32:41 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for completion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="completion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CLFD_CREDIT"/>
 *     &lt;enumeration value="CREDIT"/>
 *     &lt;enumeration value="CREDIT_EXAM"/>
 *     &lt;enumeration value="DEFENCE"/>
 *     &lt;enumeration value="EXAM"/>
 *     &lt;enumeration value="NOTHING"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "completion", namespace = "http://kosapi.feld.cvut.cz/schema/3")
@XmlEnum
public enum Completion {

    CLFD_CREDIT,
    CREDIT,
    CREDIT_EXAM,
    DEFENCE,
    EXAM,
    NOTHING,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static Completion fromValue(String v) {
        return valueOf(v);
    }

}
