//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.20 at 06:32:41 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for season.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="season">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WINTER"/>
 *     &lt;enumeration value="SUMMER"/>
 *     &lt;enumeration value="BOTH"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "season", namespace = "http://kosapi.feld.cvut.cz/schema/3")
@XmlEnum
public enum Season {

    WINTER,
    SUMMER,
    BOTH,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static Season fromValue(String v) {
        return valueOf(v);
    }

}
