//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 02:49:25 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for studyTerminationReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="studyTerminationReason">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GRADUATION"/>
 *     &lt;enumeration value="WITHDRAW"/>
 *     &lt;enumeration value="NONCOMPLIANCE"/>
 *     &lt;enumeration value="ACCREDITATION_REVOKED"/>
 *     &lt;enumeration value="ACCREDITATION_EXPIRED"/>
 *     &lt;enumeration value="EXPULSION_PAR_65"/>
 *     &lt;enumeration value="EXPULSION_PAR_67"/>
 *     &lt;enumeration value="DEATH"/>
 *     &lt;enumeration value="TRANSFER_TO_OTHER_FACULTY"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "studyTerminationReason")
@XmlEnum
public enum StudyTerminationReason {

    GRADUATION,
    WITHDRAW,
    NONCOMPLIANCE,
    ACCREDITATION_REVOKED,
    ACCREDITATION_EXPIRED,
    EXPULSION_PAR_65,
    EXPULSION_PAR_67,
    DEATH,
    TRANSFER_TO_OTHER_FACULTY,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static StudyTerminationReason fromValue(String v) {
        return valueOf(v);
    }

}
