//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 02:49:25 PM CEST 
//


package cz.cvut.fel.kos.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for student complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="student">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="branch" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="department" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="faculty" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grade" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="interruptedUntil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="personalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="programme" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="studyForm" type="{http://kosapi.feld.cvut.cz/schema/3}studyForm"/>
 *         &lt;element name="studyGroup" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="studyPlan" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="studyState" type="{http://kosapi.feld.cvut.cz/schema/3}studyState"/>
 *         &lt;element name="supervisor" type="{http://kosapi.feld.cvut.cz/schema/3}link"/>
 *         &lt;element name="studyTerminationReason" type="{http://kosapi.feld.cvut.cz/schema/3}studyTerminationReason"/>
 *         &lt;element name="titlesPost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titlesPre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "student", propOrder = {
    "branch",
    "department",
    "email",
    "faculty",
    "firstName",
    "grade",
    "interruptedUntil",
    "lastName",
    "personalNumber",
    "programme",
    "studyForm",
    "studyGroup",
    "studyPlan",
    "studyState",
    "supervisor",
    "studyTerminationReason",
    "titlesPost",
    "titlesPre",
    "username"
})
public class Student {

    protected Link branch;
    protected Link department;
    protected String email;
    protected Link faculty;
    protected String firstName;
    protected Integer grade;
    protected String interruptedUntil;
    protected String lastName;
    protected String personalNumber;
    protected Link programme;
    protected StudyForm studyForm;
    protected Integer studyGroup;
    protected Link studyPlan;
    protected StudyState studyState;
    protected Link supervisor;
    protected StudyTerminationReason studyTerminationReason;
    protected String titlesPost;
    protected String titlesPre;
    protected String username;

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setBranch(Link value) {
        this.branch = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setDepartment(Link value) {
        this.department = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the faculty property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getFaculty() {
        return faculty;
    }

    /**
     * Sets the value of the faculty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setFaculty(Link value) {
        this.faculty = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the grade property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrade(Integer value) {
        this.grade = value;
    }

    /**
     * Gets the value of the interruptedUntil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterruptedUntil() {
        return interruptedUntil;
    }

    /**
     * Sets the value of the interruptedUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterruptedUntil(String value) {
        this.interruptedUntil = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the personalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalNumber() {
        return personalNumber;
    }

    /**
     * Sets the value of the personalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalNumber(String value) {
        this.personalNumber = value;
    }

    /**
     * Gets the value of the programme property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getProgramme() {
        return programme;
    }

    /**
     * Sets the value of the programme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setProgramme(Link value) {
        this.programme = value;
    }

    /**
     * Gets the value of the studyForm property.
     * 
     * @return
     *     possible object is
     *     {@link StudyForm }
     *     
     */
    public StudyForm getStudyForm() {
        return studyForm;
    }

    /**
     * Sets the value of the studyForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyForm }
     *     
     */
    public void setStudyForm(StudyForm value) {
        this.studyForm = value;
    }

    /**
     * Gets the value of the studyGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStudyGroup() {
        return studyGroup;
    }

    /**
     * Sets the value of the studyGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStudyGroup(Integer value) {
        this.studyGroup = value;
    }

    /**
     * Gets the value of the studyPlan property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getStudyPlan() {
        return studyPlan;
    }

    /**
     * Sets the value of the studyPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setStudyPlan(Link value) {
        this.studyPlan = value;
    }

    /**
     * Gets the value of the studyState property.
     * 
     * @return
     *     possible object is
     *     {@link StudyState }
     *     
     */
    public StudyState getStudyState() {
        return studyState;
    }

    /**
     * Sets the value of the studyState property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyState }
     *     
     */
    public void setStudyState(StudyState value) {
        this.studyState = value;
    }

    /**
     * Gets the value of the supervisor property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getSupervisor() {
        return supervisor;
    }

    /**
     * Sets the value of the supervisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setSupervisor(Link value) {
        this.supervisor = value;
    }

    /**
     * Gets the value of the studyTerminationReason property.
     * 
     * @return
     *     possible object is
     *     {@link StudyTerminationReason }
     *     
     */
    public StudyTerminationReason getStudyTerminationReason() {
        return studyTerminationReason;
    }

    /**
     * Sets the value of the studyTerminationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyTerminationReason }
     *     
     */
    public void setStudyTerminationReason(StudyTerminationReason value) {
        this.studyTerminationReason = value;
    }

    /**
     * Gets the value of the titlesPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlesPost() {
        return titlesPost;
    }

    /**
     * Sets the value of the titlesPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlesPost(String value) {
        this.titlesPost = value;
    }

    /**
     * Gets the value of the titlesPre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlesPre() {
        return titlesPre;
    }

    /**
     * Sets the value of the titlesPre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlesPre(String value) {
        this.titlesPre = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

}
